name: play_install_referrer
description: >
  A Flutter plugin for the Android Play Install Referrer API.
  You can use it to securely retrieve referral content from Google Play.
version: 0.5.0
homepage: https://chunkytofustudios.com
repository: https://github.com/ChunkyTofuStudios/play_install_referrer

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.chunkytofustudios.play_install_referrer
        pluginClass: PlayInstallReferrerPlugin
